### ISSUE TITLE
バインディングのコメントが表示されない

### ISSUE THREAD

**Issue by Funny-Silkie** [altseed/Altseed2-csharp#10]
```
/// <summary>
///
/// </summary>
```
の外枠は表示されても中身のコメントが表示されない模様

**Comment by wistnki** [comment]
コメント出力のデフォルト言語が英語になっていたため。
https://github.com/altseed/Altseed2-csharp/commit/cad4f73b63d286f679847f385703dab7b306733a
にて修正。
