### ISSUE TITLE
構造体の定義を二箇所でしている

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2-csharp#2]
https://github.com/altseed/Altseed2-csharp/blob/master/Engine/Engine.cs

https://github.com/altseed/Altseed2-csharp/blob/master/Engine/Struct.cs

で、どちらも `Sequential` のAttributeがついているので、変換する必要はないのでは？

**Comment by wistnki** [comment]
名前空間が違うので別物扱いになってる。
まあusingすればよいとかいう話もあるが、
ユーザは基本Coreを触る必要がないので。

**Comment by wistnki** [comment]
https://github.com/altseed/Altseed2-csharp/commit/298046d1dbde3fa6200e436d8f09b08d723e2a1d
